/*
 * Copyright 2019 Random Logic Consulting Services and Paul G. Allen. All rights reserved.
 */
package com.randomlogic.rlpay.model.domain.company.entity;
// Generated Jan 7, 2019 10:43:39 AM by Hibernate Tools 4.3.1


import com.randomlogic.rlpay.model.domain.interfaces.IConfiguration;
import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Configuration generated by hbm2java
 */
@Entity
@Table
(
    name = "Configuration",
    uniqueConstraints = @UniqueConstraint (columnNames = "idConfiguration")
)
public class Configuration implements IConfiguration, Serializable
{
    private static final long serialVersionUID = 7344055601161960295L;

    private ConfigurationId id;

    private String cfgvalue;
    private int enclevel = 0;
    private String enctype = "0";

    public Configuration()
    {
        id = new ConfigurationId();
    }

    public Configuration (String key)
    {
       this.id = new ConfigurationId();
       this.id.setConfigKey (key);
    }

    public Configuration (ConfigurationId id, String value)
    {
       this.id = id;
       this.cfgvalue = value;
    }

        @EmbeddedId
    @AttributeOverrides
    (
        {
            @AttributeOverride (name = "idConfiguration", column=@Column (name = "idconfiguration", unique = true, nullable = false)),
            @AttributeOverride (name = "configKey", column = @Column (name = "configkey", nullable = false, length = 45))
        }
    )
    @Override
    public ConfigurationId getId()
    {
        return this.id;
    }

    @Override
    public void setId (ConfigurationId id)
    {
        this.id = id;
    }

    /**
     *
     * @return
     */
    @Column (name = "cfgvalue", nullable = false)
    @Override
    public String getCfgvalue()
    {
        return this.cfgvalue;
    }

    @Override
    public void setCfgvalue (String cfgvalue)
    {
        this.cfgvalue = cfgvalue;
    }

    @Column (name = "enclevel", nullable = false)
    @Override
    public int getEnclevel()
    {
        return this.enclevel;
    }

    @Override
    public void setEnclevel (int enclevel)
    {
        this.enclevel = enclevel;
    }

    @Column (name = "enctype", nullable = false)
    @Override
    public String getEnctype()
    {
        return this.enctype;
    }

    @Override
    public void setEnctype (String enctype)
    {
        this.enctype = enctype;
    }
}
