/*
 * Copyright 2019 Random Logic Consulting Services and Paul G. Allen. All rights reserved.
 */
package com.randomlogic.rlpay.model.domain.company.entity;
// Generated Jan 7, 2019 10:43:39 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserId generated by hbm2java
 */
@Embeddable
public class UserId  implements Serializable
{
    private int idUser = 0;
    private String uid;
    private String deviceid;

    public UserId()
    {
    }

    public UserId (int idUser, String uid, String deviceid)
    {
       this.idUser = idUser;
       this.uid = uid;
       this.deviceid = deviceid;
    }


    @Column (name="iduser", unique=true, nullable=false)
    public int getIdUser()
    {
        return this.idUser;
    }

    public void setIdUser (int idUser)
    {
        this.idUser = idUser;
    }

    @Column (name="userid", nullable=false, length=45)
    public String getUid()
    {
        return this.uid;
    }

    public void setUid (String uid)
    {
        this.uid = uid;
    }

    @Column (name="deviceid", nullable=false, length=64)
    public String getDeviceid()
    {
        return this.deviceid;
    }

    public void setDeviceid (String deviceid)
    {
        this.deviceid = deviceid;
    }

    @Override
    public boolean equals (Object other)
    {
        if ((this == other ))
        {
            return true;
        }

        if ((other == null))
        {
            return false;
        }

        if (!(other instanceof UserId))
        {
            return false;
        }

        UserId castOther = (UserId) other;

        return (this.getIdUser() == castOther.getIdUser())
                && ((this.getUid().equals (castOther.getUid())) || (this.getUid() != null && castOther.getUid() != null && this.getUid().equals(castOther.getUid())))
                && ((this.getDeviceid().equals (castOther.getDeviceid())) || (this.getDeviceid()!=null && castOther.getDeviceid() != null && this.getDeviceid().equals(castOther.getDeviceid())));
    }

    @Override
    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getIdUser();
        result = 37 * result + ( getUid() == null ? 0 : this.getUid().hashCode() );
        result = 37 * result + ( getDeviceid() == null ? 0 : this.getDeviceid().hashCode() );
        return result;
    }
}


