/*
 * Copyright 2019 Random Logic Consulting Services and Paul G. Allen. All rights reserved.
 */
package com.randomlogic.rlpay.model.domain.company.entity;
// Generated Jan 7, 2019 10:43:39 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AuthorizationId generated by hbm2java
 */
@Embeddable
public class AuthorizationId implements Serializable
{
    private int idAuthorization;
    private String method;

    public AuthorizationId()
    {
    }

    public AuthorizationId(int idAuthorization, String method)
    {
       this.idAuthorization = idAuthorization;
       this.method = method;
    }

    @Column(name="idAuthorization", unique=true, nullable=false)
    public int getIdAuthorization()
    {
        return this.idAuthorization;
    }

    public void setIdAuthorization(int idAuthorization)
    {
        this.idAuthorization = idAuthorization;
    }

    @Column(name="method", nullable=false)
    public String getMethod()
    {
        return this.method;
    }

    public void setMethod(String method)
    {
        this.method = method;
    }

    @Override
    public boolean equals (Object other)
    {
        if ((this == other))
        {
            return true;
        }

        if ((other == null))
        {
            return false;
        }

        if (!(other instanceof AuthorizationId))
        {
            return false;
        }

        AuthorizationId castOther = (AuthorizationId) other;

        return (this.getIdAuthorization() == castOther.getIdAuthorization())
            && ((this.getMethod() == castOther.getMethod()) || (this.getMethod() != null && castOther.getMethod() != null && this.getMethod().equals(castOther.getMethod())));
    }

    @Override
    public int hashCode()
    {
        int result = 17;

        result = 37 * result + this.getIdAuthorization();
        result = 37 * result + ( getMethod() == null ? 0 : this.getMethod().hashCode() );
        return result;
    }
}


